### ISSUE TITLE
File upload opens files folder twice

### ISSUE THREAD

**Issue by danielsimao** [joshdschneider/formation#2]
I was exploring your library and came across the file upload component. If you click it twice, it opens your file explorer twice as well. Is this a native behaviour or something that could be prevented on your end?

Anyway, amazing work! Super clean library.

**Comment by danielsimao** [comment]
Also, interesting approach on your components using classes. I prefer them as functions, but I also understand why you approach this with that architecture.

**Comment by joshdschneider** [comment]
Thanks @danielsimao! What browser/OS are you using? Could be an event propagation issue.

**Comment by joshdschneider** [comment]
> Also, interesting approach on your components using classes. I prefer them as functions, but I also understand why you approach this with that architecture.

Yea I hear ya! I thought it'd be a little cleaner and more manageable as classes, but I'll probably end up rewriting them as functional components. Would eventually like to expand the library to offer some useful custom hooks.
