### ISSUE TITLE
SCSS improvements

### ISSUE THREAD

**Issue by joshdschneider** [joshdschneider/formation#6]
The current SCSS is difficult to maintain, and the global class namespaces (like `.button`) are polluted—which could cause unexpected style behavior to the applications consuming the library. I'm looking to move to something more clean and modular like [stitches](https://stitches.dev/), [emotion](https://emotion.sh/), or [css modules](https://github.com/css-modules/css-modules). Anyone have tips or suggestions?

**Comment by kysley** [comment]
@joshdschneider If you want to create a stitches theme with your current design tokens, I will be able to help convert components over :) I tried replicating your theme in stitches, but I'm not familiar enough with the tokens for me to do it well 😬
