### ISSUE TITLE
Docs repo link is broken

### ISSUE THREAD

**Issue by programmerraja** [joshdschneider/formation#7]
The docs links (https://github.com/joshdschneider/docs) that given in readme file is broken can i get proper link of that

**Comment by programmerraja** [comment]
@joshdschneider the link shared is for docs page but I need repo link can I get it or can you tell how you create a doc which tool you have used

**Comment by joshdschneider** [comment]
Ah, docs repo was private—I just made it [public](https://github.com/joshdschneider/formation-docs). For what it's worth, that was a long time ago. I'd probably use a framework like [Nextra](https://nextra.site/) now.
